### ISSUE TITLE
Graphviz for drawing als alternative to networkx

### ISSUE THREAD

**Issue by quaxquax** [artiste-qb-net/quantum-fog#5]
Drawing should default to graphviz module when available otherwise fall back on networkx.

**Comment by quaxquax** [comment]
Investigated this a bit.  At the current release level networkx is not playing nice with graphviz.  Even if both modules work fine on their own they don't play nicely together.  I observe the same behavior as described in this stackoverflow track:
http://stackoverflow.com/questions/35279733/what-could-cause-networkx-pygraphviz-to-work-fine-alone-but-not-together

**Comment by quaxquax** [comment]
Running the pygraphviz test also gives me a seg fault, which apparently is a know issue with Python 3.5 and 3.4:
https://github.com/pygraphviz/pygraphviz/issues/84

This is on an up-to-date Ubuntu/Linux system.

**Comment by quaxquax** [comment]
Can now for the first time create a dot file, ran into some more issues that I will document and test before creating a pull request.

**Comment by quaxquax** [comment]
Pull the latest repo to retrace these steps. The networkx rendering works, but I get the following error message:

Traceback (most recent call last):
  File "/home/quax/projects/quantum-fog/graphs/BayesNet.py", line 158, in <module>
    bnet.write_dot(path1)
  File "/home/quax/projects/quantum-fog/graphs/Graph.py", line 258, in write_dot
    nx.write_dot(self.get_nx_graph(), path)
AttributeError: module 'networkx' has no attribute 'write_dot'

**Comment by quaxquax** [comment]
The networkx write_dot issue seems to be related to this: https://github.com/nipy/nipype/issues/1350

**Comment by quaxquax** [comment]
While related to this feature request the networkx issue is a separate bug.  Hence opened a new issue for this.

**Comment by quaxquax** [comment]
Got graphviz to work nicely with QFog in Jupyter.  Trick was to use anaconda and install graphviz via pipe rather than conda install.

![dot_jupyter](https://cloud.githubusercontent.com/assets/5298290/21132000/c6fc1706-c0df-11e6-9534-e9133695dbc7.png)

**Comment by quaxquax** [comment]
Since this now works in Jupyter where is matters the most. I will close this issue.

**Comment by rrtucci** [comment]
C'est magnifique. On my part, I have begun rewriting the quantum compiler in python.I am pretty sure of how to do it. Since I've done it before in c++ and java, there islittle uncertainty in my mind. It's just a matter of translating already existing subroutines from c++ and java to python. I think i can do it in a month or less--- notifications@github.com wrote:From: Henning Dekant <notifications@github.com>To: artiste-qb-net/quantum-fog <quantum-fog@noreply.github.com>Subject: Re: [artiste-qb-net/quantum-fog] Graphviz for drawing als alternative to networkx (#5)Date: Mon, 12 Dec 2016 23:57:16 -0800Got graphviz to work nicely with QFog in Jupyter.  Trick was to use anaconda and install graphviz via pipe rather than conda install.
